apiVersion: 1

datasources:
  - name: WardHub-Prometheus
    type: prometheus
    uid: wardenhub-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "60s"
